## [머신러닝 강의 15] Linear Regression (III)

실제 예제로 선형 회귀 계산


In [11]:
import numpy as np

In [12]:
x_data = np.array([1, 2, 3, 4, 5]).reshape(5,1)
t_data = np.array([2, 3, 4, 5, 6]).reshape(5,1)

# raw_data = [ [1, 2], [2, 3], [3, 4], [4, 5], [5, 6] ]
print(x_data)
print(t_data)

print("x_data.shape = ", x_data.shape, ", t_data.shape = ", t_data.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[2]
 [3]
 [4]
 [5]
 [6]]
x_data.shape =  (5, 1) , t_data.shape =  (5, 1)


In [13]:
W = np.random.rand(1,1)
b = np.random.rand(1)
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.65783674]] , W.shape =  (1, 1) , b =  [0.50266849] , b.shape =  (1,)


In [ ]:
W = np.random.rand(1,1)
b = np.random.rand(1)
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.65783674]] , W.shape =  (1, 1) , b =  [0.50266849] , b.shape =  (1,)


In [14]:
def loss_func(x, t):
    y = np.dot(x,W) + b

    return ( np.sum( (t - y)**2 ) ) / ( len(x) )
    # 1/n x sigma( ti - yi )**2 )

In [15]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)

        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)

        x[idx] = tmp_val
        it.iternext()

    return grad

In [16]:
# 손실함수 값 계산 함수
# 입력변수 x, t : numpy type
def error_val(x, t):
    y = np.dot(x,W) + b

    return ( np.sum( (t - y)**2 ) ) / ( len(x) )

# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
# 입력변수 x : numpy type
def predict(x):
    y = np.dot(x,W) + b

    return y

In [17]:
learning_rate = 1e-2  # 발산하는 경우, 1e-3 ~ 1e-6 등으로 바꾸어서 실행

f = lambda x : loss_func(x_data,t_data)

print("Initial error value = ", error_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b )

for step in  range(8001):

    W -= learning_rate * numerical_derivative(f, W)

    b -= learning_rate * numerical_derivative(f, b)

    if (step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ",b )

Initial error value =  2.5561826790562043 Initial W =  [[0.65783674]] 
 , b =  [0.50266849]
step =  0 error value =  1.5149598536837694 W =  [[0.76295255]] , b =  [0.52683796]
step =  400 error value =  0.0018406722368661688 W =  [[1.02786025]] , b =  [0.89944029]
step =  800 error value =  0.00011744577071632425 W =  [[1.00703745]] , b =  [0.97459879]
step =  1200 error value =  7.493734507904549e-06 W =  [[1.00177765]] , b =  [0.9935837]
step =  1600 error value =  4.781445643592986e-07 W =  [[1.00044903]] , b =  [0.99837925]
step =  2000 error value =  3.0508449983908997e-08 W =  [[1.00011342]] , b =  [0.9995906]
step =  2400 error value =  1.946619474088672e-09 W =  [[1.00002865]] , b =  [0.99989659]
step =  2800 error value =  1.2420583080829638e-10 W =  [[1.00000724]] , b =  [0.99997388]
step =  3200 error value =  7.925066307131083e-12 W =  [[1.00000183]] , b =  [0.9999934]
step =  3600 error value =  5.056660828633405e-13 W =  [[1.00000046]] , b =  [0.99999833]
step =  4000 err

In [18]:
predict(43)

array([[44.]])