## [머신러닝 강의 07] 파이썬(Python) Numpy (II)

2025/3/13

In [ ]:
# 경로 확인 용.
import os
print(os)


<module 'os' from '/Users/yhlee/miniforge3/envs/ml_39/lib/python3.9/os.py'>


In [1]:

import numpy as np

A = np.array([ [1, 2, 3], [4, 5, 6] ])  # 2X3 행렬
B = np.array([ [-1, -2], [-3, -4], [-5, -6] ])  # 3X2 행렬

# (2X3) dot porduct (3X2) == (2X2) 행렬
C = np.dot(A, B)  # 행렬 곱 수행

# matrix A, B 형상 출력 => shape
print("A.shape ==", A.shape, ", B.shape ==", B.shape)
print("C.shape ==", C.shape)
print(C)

A.shape == (2, 3) , B.shape == (3, 2)
C.shape == (2, 2)
[[-22 -28]
 [-49 -64]]


사칙 연산은 행렬 원소 개수가 동일해야만 연산 가능.
도트 프로덕은 이 크기 제한이 덜함.

-> 다양한 특성을 갖는 필터 개발이 가능.

사칙 연산에서도 브로드캐스트를 이용하면 연산은 됨.
차원이 낮은 쪽을 큰 쪽에 맞춰 확장 시켜줄 수 있음.

브로드캐스트 는 행렬곱에는 적용 안된다!!

In [3]:
# scalar broadcast

A = np.array([ [1, 2], [3, 4] ])
b = 5

print(A)
print(A+b)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


In [5]:
# matrix broadcast

C = np.array([ [1, 2], [3, 4] ])
D = np.array([4, 5])

print(C)
print(D)
print(C+D)

[[1 2]
 [3 4]]
[4 5]
[[5 7]
 [7 9]]


In [6]:
# 전치행렬

A = np.array([ [1, 2], [3, 4], [5, 6] ])  # 3X2행렬

B = A.T    # A의 전치행렬, 2X3 행렬
# T 가 연산자인가??
# 마치 속성 처럼 보이는데...


print("A.shape ==", A.shape, ", B.shape ==", B.shape)
print(A)
print(B)

A.shape == (3, 2) , B.shape == (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [8]:
# vector 전치행렬

C = np.array([1, 2, 3, 4, 5])  # vector, matrix 아님
D = C.T      # C 는 vector 이므로 transpose 않됨

# 벡터는 T가 안되지만, 같은 데이터를 가진 행렬은 T가 된다.
E = C.reshape(1, 5)    #  1X5 matrix
F = E.T    # E 의 전치행렬

print(C)
print("C.shape ==", C.shape, ", D.shape ==", D.shape)
print(D)

print(E)
print("E.shape ==", E.shape, ". F.shape ==", F.shape)
print(F)

[1 2 3 4 5]
C.shape == (5,) , D.shape == (5,)
[1 2 3 4 5]
[[1 2 3 4 5]]
E.shape == (1, 5) . F.shape == (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [19]:
# reshape

A = np.array([10, 20, 30, 40, 50, 60]).reshape(3, 2)

print("A.shape ==", A.shape)
print(A)

A.shape == (3, 2)
[[10 20]
 [30 40]
 [50 60]]


In [20]:
# indexing / slicing
print(A)

# 1행 1열 원소
print("A[0, 0] ==", A[0, 0], ", A[0][0] ==", A[0][0])
# 3행 2열
print("A[2, 1] ==", A[2, 1], ", A[2][1] ==", A[2][1])
# 인덱스 0:1 행,
print("-- A[0:1, 0:1] ==\n%s" % A[0:1, 0:1])
print("++ A[0:-1, 1:2] ==\n%s" % A[0:-1, 1:2])
# 모든 행 1열
print("** A[ :, 0] ==", A[:, 0])
# 이 결과가 matrix가 아닌 vector가 된다는건 흥미로움.
# 어느 차원에서든, : 가 아닌 정수 인덱싱을 하면 차원이 하나 줄어든다.

# 모든 행, 모든 열. 즉 A 와 동일.
print(">> A[ :, :] ==\n%s" % A[:, :])

[[10 20]
 [30 40]
 [50 60]]
A[0, 0] == 10 , A[0][0] == 10
A[2, 1] == 60 , A[2][1] == 60
-- A[0:1, 0:1] ==
[[10]]
++ A[0:-1, 1:2] ==
[[20]
 [40]]
** A[ :, 0] == [10 30 50]
>> A[ :, :] ==
[[10 20]
 [30 40]
 [50 60]]


In [23]:
# iterator 예제
import numpy as np

A = np.array([ [10, 20, 30, 40], [50, 60, 70, 80] ])

print(A, "\n")
print("A.shape ==", A.shape, "\n")

# 행렬 A 의 itrator 생성

it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])
print(it)

while not it.finished:

    idx = it.multi_index

    print("%s: current value => %s" % (idx, A[idx]))

    it.iternext()

[[10 20 30 40]
 [50 60 70 80]] 

A.shape == (2, 4) 

(0, 0): current value => 10
(0, 1): current value => 20
(0, 2): current value => 30
(0, 3): current value => 40
(1, 0): current value => 50
(1, 1): current value => 60
(1, 2): current value => 70
(1, 3): current value => 80


nditer 는 요소가 저장된 순서대로 순회 하는 것으로 보임.

multi_index 플래그가 없으면 어떻게 되는가? <br>
=> index 값이 그냥 1차원 배열 처럼 증가. 실제 배열 요소의 순회 순서는 차이가 없음.


In [26]:
A = np.array([ [10, 20, 30 ], [40, 50, 60] ])

print(A, "\n")

it = np.nditer(A,
            flags=['multi_index'],
            op_flags=['readwrite'])

while not it.finished:
    idx = it.multi_index
    print("%s: %s" % (idx, A[idx]))
    it.iternext()

[[10 20 30]
 [40 50 60]] 

(0, 0): 10
(0, 1): 20
(0, 2): 30
(1, 0): 40
(1, 1): 50
(1, 2): 60
