## [머신러닝 강의 09] 머신러닝 수치미분 (I)


10장:
https://www.youtube.com/watch?v=3ELMIbGTIDs&list=PLS8gIc2q83OjStGjdTF2LZtc0vefCAbnX&index=10

11장:




In [ ]:
import numpy as np

'''
Args:
    f: 미분하고자 하는 함수. 입력 값이 x 이어야 함.
    x: 함수 f의 입력변수의 값. (N-차 벡터, 또는 행렬 일 수 있음).
        이 x 위치에서의 미분 값을 구하는 것임.
        numpy array 타입.
Note:
    x가 행렬일 수도 있음. 예: shape이 (2,2)라면 총 4개의 변수가 있는 것임.
    이 경우, 아래 while 내에서 iterator는 총 4번을 반복하게 됨.
'''
def numerical_derivative(f, x):    # 수치미분 debug version
    delta_x = 1e-4
    grad = np.zeros_like(x)
    # x와 동일한 shape을 가지는 zero 벡터 또는 행렬

    print("debug 1. initial input variable =", x)
    print("debug 2. initial grad =", grad)
    print("=======================================")

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx = it.multi_index

        print("debug 3. idx = ", idx, ", x[idx] = ", x[idx])

        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)   # f(x+delta_x)

        x[idx] = tmp_val - delta_x
        fx2 = f(x)   # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)

        print("debug 4. grad[idx] = ", grad[idx])
        print("debug 5. grad = ", grad)
        print("=======================================")

        x[idx] = tmp_val
        it.iternext()

    return grad

### 실습 1

f(x) = x**2

In [ ]:
# 입력변수 1 개인 함수 f(x) = x**2
def func1(input_obj):
    # 여기에서 input_obj 는 numpy 객체. (예: np.array)
    x = input_obj[0]

    return  x**2


# x = 3.0 에서의 편미분 값
numerical_derivative( func1, np.array([3.0]) )

debug 1. initial input variable = [3.]
debug 2. initial grad = [0.]
debug 3. idx =  (0,) , x[idx] =  3.0
debug 4. grad[idx] =  6.000000000012662
debug 5. grad =  [6.]


array([6.])

In [8]:
# yhlee 추가
numerical_derivative( func1, np.array([3.0,4]) )

debug 1. initial input variable = [3. 4.]
debug 2. initial grad = [0. 0.]
debug 3. idx =  (0,) , x[idx] =  3.0
debug 4. grad[idx] =  6.000000000012662
debug 5. grad =  [6. 0.]
debug 3. idx =  (1,) , x[idx] =  4.0
debug 4. grad[idx] =  0.0
debug 5. grad =  [6. 0.]


array([6., 0.])

이 값이 원하는 값인가?/////

위 결과에 나온 경고:
/var/folders/gk/5yll9c4s4574ff6wr892k56r0000gn/T/ipykernel_63600/552317243.

py:25: DeprecationWarning: 
Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)


In [ ]:
# 입력변수 2 개인 함수 f(x, y) = 2x + 3xy + y^3
def func1(input_obj):

    x = input_obj[0]
    y = input_obj[1]

    return  ( 2*x + 3*x*y + np.power(y,3) )


# (x,y) = (1.0, 2.0) 에서의 편미분 값
input = np.array([1.0, 2.0])

numerical_derivative( func1, input )

debug 1. initial input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. idx =  (0,) , x[idx] =  1.0
debug 4. grad[idx] =  7.999999999990237
debug 5. grad =  [8. 0.]
debug 3. idx =  (1,) , x[idx] =  2.0
debug 4. grad[idx] =  15.000000010019221
debug 5. grad =  [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [ ]:
# 입력변수 4 개인 함수
# f(w,x,y,z) = wx + xyz + 3w + zy^2
# input_obj 는 행렬
def func1(input_obj):

    w = input_obj[0, 0]
    x = input_obj[0, 1]
    y = input_obj[1, 0]
    z = input_obj[1, 1]

    return  ( w*x + x*y*z + 3*w + z*np.power(y,2) )

# 입력을 2X2 행렬로 구성함
input = np.array([ [1.0, 2.0], [3.0, 4.0] ])

numerical_derivative( func1, input )

debug 1. initial input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. idx =  (0, 0) , x[idx] =  1.0
debug 4. grad[idx] =  5.000000000023874
debug 5. grad =  [[5. 0.]
 [0. 0.]]
debug 3. idx =  (0, 1) , x[idx] =  2.0
debug 4. grad[idx] =  13.00000000000523
debug 5. grad =  [[ 5. 13.]
 [ 0.  0.]]
debug 3. idx =  (1, 0) , x[idx] =  3.0
debug 4. grad[idx] =  32.00000000006753
debug 5. grad =  [[ 5. 13.]
 [32.  0.]]
debug 3. idx =  (1, 1) , x[idx] =  4.0
debug 4. grad[idx] =  15.000000000000568
debug 5. grad =  [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])

앞의 예제와 동일한데 다만 func1 의 input_obj 를 행렬 대신 벡터로도 계산해 보기로 함.

In [5]:
# 입력변수 4 개인 함수
# f(w,x,y,z) = wx + xyz + 3w + zy^2
def func1(input_obj):

    w = input_obj[0]
    x = input_obj[1]
    y = input_obj[2]
    z = input_obj[3]

    return  ( w*x + x*y*z + 3*w + z*np.power(y,2) )

input = np.array([ 1.0, 2.0, 3.0, 4.0 ])

numerical_derivative( func1, input )

debug 1. initial input variable = [1. 2. 3. 4.]
debug 2. initial grad = [0. 0. 0. 0.]
debug 3. idx =  (0,) , x[idx] =  1.0
debug 4. grad[idx] =  5.000000000023874
debug 5. grad =  [5. 0. 0. 0.]
debug 3. idx =  (1,) , x[idx] =  2.0
debug 4. grad[idx] =  13.00000000000523
debug 5. grad =  [ 5. 13.  0.  0.]
debug 3. idx =  (2,) , x[idx] =  3.0
debug 4. grad[idx] =  32.00000000006753
debug 5. grad =  [ 5. 13. 32.  0.]
debug 3. idx =  (3,) , x[idx] =  4.0
debug 4. grad[idx] =  15.000000000000568
debug 5. grad =  [ 5. 13. 32. 15.]


array([ 5., 13., 32., 15.])